Update Apartado8

diff --git a/Apartado8 b/Apartado8
--- a/Apartado8
+++ b/Apartado8
@@ -7,4 +7,19 @@
   00 19 * * 1-2-3-4-5 tar -czvf /root /root
 
 #Punto 2
-  
+  #!/bin/bash
+  #Poner la ip que deseamos testear
+  gateway="192.168.209.240"
+  log="/home/`whoami`/regPing-to-computer.txt"oi
+  error="/home/`whoami`/errorPing-to-computer.txt"
+  ping=`ping -c 3 $gateway`
+ 
+  if [ $? -eq 0 ]
+  then
+  `date >> $log`
+  `echo -e $ping "\n">> $log` 
+  else
+   `echo -e "\n ¡¡¡¡ ERROR CON LA CONEXION !!!!" >> $error`
+  `date >> $error`
+  `echo $ping >> $error`
+  fi
